image: tiangolo/uvicorn-gunicorn-fastapi:python3.11

stages:
  - deploy

pushToDockerRegistry:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "develop"
  image: docker:20.10.12
  services:
    - docker:20.10.12-dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG server
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
